# Generated by Django 5.1.1 on 2024-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='product',
            name='lease_duration',
            field=models.CharField(choices=[('short', 'Краткосрочная аренда'), ('long', 'Долгосрочная аренда')], default='short', max_length=50, verbose_name='Срок аренды'),
        ),
        migrations.AddField(
            model_name='product',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Можно с животными'),
        ),
    ]
